# Generated by Django 4.1.3 on 2022-12-06 19:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0002_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 19, 44, 28, 888293, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
