# Generated by Django 4.1.3 on 2022-12-06 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquetes', '0003_alter_question_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 21, 29, 203618, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
