# Generated by Django 4.1.3 on 2022-12-06 19:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 19, 44, 28, 949294, tzinfo=datetime.timezone.utc), verbose_name='data de publicação')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=100)),
                ('avatar', models.ImageField(upload_to='avatar')),
                ('tipo', models.IntegerField(default=3)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='thumbnail')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 19, 44, 28, 950293, tzinfo=datetime.timezone.utc), verbose_name='data de publicação')),
                ('categoria', models.CharField(max_length=100)),
                ('edicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.edicao')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='edicao',
            name='usuario_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.usuario'),
        ),
    ]
