# Generated by Django 4.1.3 on 2022-12-06 20:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 21, 29, 245617, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 21, 29, 245617, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conteudo', models.CharField(max_length=500)),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 21, 29, 245617, tzinfo=datetime.timezone.utc), verbose_name='data de publicação')),
                ('curtidas', models.IntegerField(default=0)),
                ('edicao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.edicao')),
                ('noticia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.noticia')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inrite.usuario')),
            ],
        ),
    ]
