# Generated by Django 4.1.3 on 2022-12-06 20:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0002_alter_edicao_data_alter_noticia_data_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 40, 22, 496334, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 40, 22, 495334, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 40, 22, 496334, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.SmallIntegerField(default=3),
        ),
    ]
