# Generated by Django 4.1.3 on 2022-12-06 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0003_alter_comentario_data_alter_edicao_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 43, 7, 140407, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 43, 7, 139407, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 43, 7, 140407, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='thumbnail',
            field=models.ImageField(upload_to='media/thumbnail'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='avatar',
            field=models.ImageField(upload_to='media/avatar'),
        ),
    ]
