# Generated by Django 4.1.3 on 2022-12-06 20:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inrite', '0004_alter_comentario_data_alter_edicao_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 55, 42, 83760, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='edicao',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 55, 42, 82761, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 20, 55, 42, 83760, tzinfo=datetime.timezone.utc), verbose_name='data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='descricao',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('1', 'Administrador'), ('2', 'Colunista'), ('3', 'Leitor')], default=3, max_length=1),
        ),
    ]
